# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
  name: local

variables:
  JAVA_HOME: "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"

steps:
  - script: |
      echo "Setting JAVA_HOME"
      export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
    displayName: 'Set JAVA_HOME'

  - task: Maven@3
    env:
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
    inputs:
      targetType: 'inline'
      script: |
        echo "Setting JAVA_HOME"
        export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
      mavenPomFile: 'myapp/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      javaVersionSelection: '21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      jdkDestinationDirectory: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunPlatform: 'Java'
      testRunFramework: 'JUnit'
      testRunBuildPlatform: 'Java'
      branchName: 'master'
      goals: 'package'
      
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: Maven@3
    env:
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
    inputs:
      targetType: 'inline'
      script: |
        echo "Setting JAVA_HOME"
        export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"    
      mavenPomFile: 'myapp/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      javaVersionSelection: '21'
      jdkDestinationDirectory: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
      jdkArchitectureOption: 'x64'
      mavenAuthenticateFeed: true
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'deploy'
