apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.App.planet_name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.App.planet_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.App.planet_name }}
    spec:
      containers:
        - name: {{ .Values.App.planet_name | quote | default "keplr186f" }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          # command: [{{ .Values.Execute.binary | quote }}, {{ .Values.Execute.binary | quote }}, {{ .Values.Execute.path | quote }}]
          env:
            - name: APP_OUTPUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: app_output
