apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Values.namespace | default }}
data:
  app_output: {{ .Values.App.Output | default "Hello World !" | quote }}
  app_version: {{ .Values.App.Version | default "1.0.0" | quote }}
