# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package - Java maven build and publish artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: 'maven' # cache Maven local dependencies and build outputs to speed up workflows
    - name: Build with Maven
      run: mvn -B package --file myapp/pom.xml

  publish-job:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - run: mvn --batch-mode --update-snapshots verify --file myapp/pom.xml
    - run: mkdir playground-maven && cp /*.jar playground-maven
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-pg-maven
        path: playground-maven
      
      
